name: Checks

on:
    - pull_request

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install deps
              run: bun install --frozen-lockfile
            - name: Prisma Generate
              run: bun prisma generate
            - name: Run build
              run: bun run build
